<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    <meta
        http-equiv="X-UA-Compatible"
        content="ie=edge"
    >
    <title>Local Chatbot Testing</title>
    <style>
        :root {
            color-scheme: light;
            --bg: #f4f6f8;
            --surface: #ffffff;
            --text: #1f2937;
            --muted: #6b7280;
            --border: #e5e7eb;
            --accent: #0f766e;
        }

        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            min-height: 100vh;
            font-family: Georgia, "Times New Roman", serif;
            color: var(--text);
            background:
                radial-gradient(circle at top left, rgba(15, 118, 110, 0.08), transparent 40%),
                linear-gradient(180deg, #eef2f5 0%, var(--bg) 100%);
        }

        main {
            width: min(920px, calc(100% - 2rem));
            margin: 0 auto;
            padding: 3rem 0 6rem;
        }

        h1 {
            margin: 0 0 0.5rem;
            font-size: clamp(2rem, 4vw, 2.75rem);
            letter-spacing: -0.03em;
        }

        .lead {
            margin: 0 0 2rem;
            max-width: 42rem;
            color: var(--muted);
            font-size: 1.05rem;
            line-height: 1.6;
        }

        .panel {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 1rem;
            padding: 1.5rem;
            box-shadow: 0 10px 30px rgba(15, 23, 42, 0.04);
        }

        .panel h2 {
            margin: 0 0 0.75rem;
            font-size: 1.15rem;
        }

        .panel p,
        .panel ol {
            margin: 0 0 1rem;
            color: var(--muted);
            line-height: 1.55;
        }

        .panel ol {
            padding-left: 1.25rem;
        }

        .marker {
            display: inline-block;
            margin-bottom: 0.75rem;
            padding: 0.25rem 0.6rem;
            border-radius: 999px;
            background: rgba(15, 118, 110, 0.1);
            color: var(--accent);
            font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
            font-size: 0.75rem;
            font-weight: 700;
            letter-spacing: 0.04em;
            text-transform: uppercase;
        }

        .paste-zone {
            margin-top: 1.5rem;
            border: 2px dashed var(--border);
            border-radius: 1rem;
            padding: 1.25rem;
            background: #fafafa;
        }

        .paste-zone code {
            display: block;
            margin-top: 0.75rem;
            padding: 0.85rem 1rem;
            overflow-x: auto;
            border-radius: 0.75rem;
            background: #111827;
            color: #e5e7eb;
            font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
            font-size: 0.8rem;
            line-height: 1.5;
            white-space: pre-wrap;
        }

        .note {
            margin-top: 1rem;
            font-size: 0.95rem;
        }
    </style>

    {{--
        ============================================================
        PASTE GENERATED EMBED SCRIPT BELOW THIS COMMENT
        ============================================================
        1. Open Dashboard → AI Bots → your chatbot → Embed step
        2. Copy the generated <script defer src="..." ...></script>
        3. Paste it here (inside <head> or before </body>)
        4. Ensure script src points to THIS local Laravel origin
           e.g. http://127.0.0.1:8000/vendor/chatbot/js/external-chatbot.js
        ============================================================
    --}}

</head>
<body>
    <main>
        <p class="marker">Development only</p>
        <h1>Local Chatbot Testing</h1>
        <p class="lead">
            Simulated client website for end-to-end chatbot testing.
            Paste the embed script generated by the Laravel admin panel into this page,
            then interact with the widget exactly as a visitor would on a real site.
        </p>

        <section class="panel">
            <h2>How to use</h2>
            <ol>
                <li>Create / train / customize a chatbot in the admin dashboard.</li>
                <li>Open the Embed step and copy the generated script tag.</li>
                <li>Paste the script into the marked section in this Blade file (see HTML comment in <code>&lt;head&gt;</code>).</li>
                <li>Refresh this page and chat with the widget.</li>
            </ol>
            <p class="note">
                Do not hardcode production URLs. The embed script <code>src</code> origin
                becomes the chatbot API/iframe host, so it must match your local Laravel URL.
            </p>
        </section>

        <section class="paste-zone panel">
            <p class="marker">Embed script paste target</p>
            <h2>Manual paste location</h2>
            <p>
                Edit <code>resources/views/chatbot-test.blade.php</code> and paste the
                generated embed <code>&lt;script&gt;</code> under the comment block in
                <code>&lt;head&gt;</code> (or just before <code>&lt;/body&gt;</code>).
            </p>
            <code>
            <script defer src="http://127.0.0.1:8000/vendor/chatbot/js/external-chatbot.js" data-chatbot-uuid="99267488-fd12-4bb4-bde7-0202c699617b" data-iframe-width="420" data-iframe-height="745" data-language="en" ></script>;</code>
        </section>
    </main>
</body>
</html>
